### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by yy0c** [A-limon/pacman#5]
最近一次`git pull`之后出现如下错误，但是如果新建一个 Hexo 项目，用 Pacman 主题则没问题。

TypeError: /home/zzz/blog_hexo/themes/pacman/layout/layout.ejs:85
    83|   <body>
    84|     <header>

> > 85|       <%- partial('_partial/header') %>
> >     86|     </header>
> >     87|     <div id="container">
> >     88|       <%- body %>

/home/zzz/blog_hexo/themes/pacman/layout/_partial/header.ejs:20
    18|                     <% } %>
    19|                     <li>

> > 20|                     <% if   (theme.google_cse.enable){ %>
> >     21|                     <form class="search" action="<%- config.root %>search/index.html" method="get" accept-charset="utf-8">
> >     22|                         <label>Search</label>
> >     23|                         <input type="search" id="search" autocomplete="off" name="q" maxlength="20" placeholder="Search" />

Cannot read property 'enable' of undefined
    at eval (eval at <anonymous> (/usr/lib/node_modules/hexo/node_modules/ejs/lib/ejs.js:237:14), <anonymous>:29:1321)
    at eval (eval at <anonymous> (/usr/lib/node_modules/hexo/node_modules/ejs/lib/ejs.js:237:14), <anonymous>:30:115)
    at /usr/lib/node_modules/hexo/node_modules/ejs/lib/ejs.js:250:15
    at Object.exports.render (/usr/lib/node_modules/hexo/node_modules/ejs/lib/ejs.js:288:13)
    at module.exports (/usr/lib/node_modules/hexo/lib/plugins/renderer/ejs.js:5:14)
    at Object.exports.renderSync (/usr/lib/node_modules/hexo/lib/core/render.js:131:12)
    at render (/usr/lib/node_modules/hexo/lib/plugins/helper/partial.js:28:22)
    at Object.module.exports [as partial](/usr/lib/node_modules/hexo/lib/plugins/helper/partial.js:41:12)
    at eval (eval at <anonymous> (/usr/lib/node_modules/hexo/node_modules/ejs/lib/ejs.js:237:14), <anonymous>:29:3285)
    at eval (eval at <anonymous> (/usr/lib/node_modules/hexo/node_modules/ejs/lib/ejs.js:237:14), <anonymous>:29:3710)

**Comment by A-limon** [comment]
从报错`theme.google_cse.enable`信息来看，应该是你更新后没有配置主题目录下的`_config.yml`文件。因为配置文件也更新了。
里面有一相应的开启Google 自定义搜索的配置信息。

```
#### Custom Search
google_cse: 
 enable: true
 cx: ## your Custom Search ID
## https://www.google.com/cse/
```
